apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  labels:
    app.kubernetes.io/name: portfolio
    app.kubernetes.io/instance: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: portfolio
      app.kubernetes.io/instance: portfolio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: portfolio
        app.kubernetes.io/instance: portfolio
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: portfolio
          args:
            - "node"
            - "build"
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "dannylongeuay/ndsq-portfolio:latest"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: portfolio
            - configMapRef:
                name: portfolio
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
